name: Release CLI

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0
  
permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            rid: linux-x64
            ext: ""
          - os: windows-latest
            rid: win-x64
            ext: ".exe"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Build the CLI
        run: dotnet publish ./CS2CalloutExtractor.Cli/CS2CalloutExtractor.Cli.csproj --configuration Release --runtime ${{ matrix.rid }} --self-contained true --output ./artifacts/${{ matrix.os }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli-${{ matrix.os }}
          path: ./artifacts/${{ matrix.os }}/*${{ matrix.ext }}

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./release/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
