name: Release CLI

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            ext: ""
          - os: windows-latest
            ext: ".exe"
          - os: macos-latest
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the CLI
        run: dotnet publish ./CS2CalloutExtractor.Cli/CS2CalloutExtractor.Cli.csproj --configuration Release --runtime ${{ matrix.os }} --self-contained true --output ./artifacts/${{ matrix.os }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cli-${{ matrix.os }}
          path: ./artifacts/${{ matrix.os }}

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: cli-${{ matrix.os }}
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}